### ISSUE TITLE
Absturz beim Starten der App außerhalb der Unterrichtszeit

### ISSUE THREAD

**Issue by Volvo7700** [Volvo7700/TeachersEssentials#1]
Sobald man versucht, die App nach Ablauf der elften Stunde zu starten (nach 16:45), crasht sie direkt nach dem Öffnen und lässt sich erst wieder ab 8:00 starten.

### Also:
Sobald die App **außerhalb** des **definierten Zeitrasters** gestartet wird, erzeugt es einen Fehler und die App stürzt ab.

**Comment by MuffinHD** [comment]
Kann ich morgen oder übermorgen schauen, bin grad aber nicht zuhause.

**Comment by MuffinHD** [comment]
Also ich habe den Bug nicht

**Comment by Volvo7700** [comment]
Merkwürdig, ok
War bloß verwirrt, hab den ganzen Zeitcode mal auskommentiert, dann ging es wieder
Dann schauen wir einfach zusammen am Montag

**Comment by MuffinHD** [comment]
> Merkwürdig, ok
> War bloß verwirrt, hab den ganzen Zeitcode mal auskommentiert, dann ging es wieder
> Dann schauen wir einfach zusammen am Montag

Ich hab ne andere Abstirzursache gefunden. Da wurde das Config file nicht richtig geladen und die Schriftgröße konnte nicht gelesen werden. War nen einfacher fix, hab ich aber noch nicht comitted.

**Comment by Volvo7700** [comment]
ahhh ok, na umso besser ;D
